stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "building" #TODO

test-job:
  stage: test
  script:
    - echo "testing" #TODO

deploy-job-heroku:
  stage: deploy
  script:
    - echo "deploying to heroku" #TODO