stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - pip install -r requirements.txt
    - cd ./drpproject
    - python3 manage.py test drpapp/test

deploy-job-heroku:
  stage: deploy
  only:
    refs:
      - main
  script:
    - dpl heroku api --app $HEROKU_APP_NAME --api_key $HEROKU_API_KEY