stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - cd drp01
    - python3 manage.py test #TOCHECK

deploy-job-heroku:
  stage: deploy
  script:
    - echo "deploying to heroku" #TODO