stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - cd ./drpproject
    - python3 manage.py test drpapp/test

deploy-job-heroku:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  script:
    - dpl heroku api --app ${HEROKU_APP_NAME} --api_key ${HEROKU_API_KEY}

deploy-celery-setup:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "celeryTasks"'
  script:
    - docker build . --tag drpapp:latest --label drpapplabel --file ./Dockerfile
    - docker image prune --force --filter='label=drpapplabel'
    - docker run --detach --network host drpapp