stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - cd ./drpproject
    - pip install -r requirements.txt
    - python3 manage.py test drpapp/test

deploy-job-heroku:
  stage: deploy
  script:
    - dpl heroku api --app $HEROKU_APP_NAME --api_key $HEROKU_API_KEY