stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - cd drp01
    - python3 manage.py test

deploy-job-heroku:
  stage: deploy
  script:
    - apt update -yq
    - apt install -y ruby-dev
    - gem install dpl
    - dpl heroku api --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY